/**
 * Keys the official GFN web client locks in fullscreen so browser shortcuts
 * (Ctrl+T, Ctrl+N, etc.) reach the stream instead of the host browser.
 * @see vendor bundle wb() → navigator.keyboard.lock([...])
 */
export const FULLSCREEN_KEYBOARD_LOCK_CODES: readonly string[] = [
  "Escape",
  "F11",
  "BrowserBack",
  "BrowserForward",
  "BrowserRefresh",
  "BrowserHome",
  "BrowserFavorites",
  "BrowserSearch",
  "BrowserStop",
  "Sleep",
  "Power",
  "WakeUp",
  "KeyT",
  "KeyZ",
  "Slash",
  "Digit1",
  "Digit2",
  "Digit3",
  "Digit4",
  "Digit5",
  "Digit6",
  "Digit7",
  "Digit8",
  "Digit9",
  "KeyM",
  "KeyD",
  "KeyN",
  "KeyS",
  "KeyK",
  "KeyL",
  "Space",
  "PrintScreen",
  "LaunchApp1",
  "LaunchApp2",
  "LaunchMail",
  "Comma",
  "Semicolon",
  "ArrowLeft",
  "ArrowRight",
  "BracketLeft",
  "BracketRight",
  "KeyW",
  "KeyQ",
  "KeyR",
  "KeyY",
  "KeyO",
  "KeyP",
  "KeyF",
  "KeyG",
] as const;
