self-hosted-runner:
  labels:
    - blacksmith-2vcpu-ubuntu-2404
    - blacksmith-2vcpu-ubuntu-2404-arm
    - blacksmith-2vcpu-windows-2025
    - blacksmith-4vcpu-ubuntu-2404
    - blacksmith-4vcpu-ubuntu-2404-arm
    - blacksmith-4vcpu-windows-2025
    - blacksmith-6vcpu-macos-15
    - blacksmith-6vcpu-macos-latest
    - blacksmith-8vcpu-ubuntu-2404
    - blacksmith-8vcpu-ubuntu-2404-arm
    - opennow-release-signer

config-variables: null
