import type { JSX } from "react";

export type SettingsNavItem = {
  id: SettingsSectionId;
  label: string;
  icon: JSX.Element;
};

export type ThanksLoadState = "idle" | "loading" | "loaded" | "error";
export type StorageResetState = "idle" | "resetting" | "success" | "error";
export type GameAccountBusyAction = "link" | "unlink" | "resync";

export type SettingsSectionId = "account" | "stream" | "diagnostics" | "native-streamer" | "game" | "audio" | "input" | "console" | "interface" | "about" | "thanks";
export type SettingsSearchScopeId =
  | "account-storage"
  | "stream-region"
  | "stream-video"
  | "stream-recording"
  | "stream-diagnostics"
  | "native-streamer"
  | "game"
  | "audio"
  | "input"
  | "console"
  | "interface"
  | "about"
  | "thanks";

export const SETTINGS_SCOPE_SEARCH_TERMS: Record<SettingsSearchScopeId, readonly string[]> = {
  "account-storage": [
    "account",
    "subscription",
    "storage",
    "persistent storage",
    "cloud storage",
    "install to play",
    "reset storage",
    "storage reset",
    "connections",
    "connected accounts",
    "game accounts",
    "link accounts",
    "unlink accounts",
    "sync library",
    "steam",
    "epic",
    "ubisoft",
    "battle.net",
    "xbox",
    "gaijin",
    "region",
    "data",
    "games",
    "downloads",
    "available",
    "used",
  ],
  "stream-region": [
    "stream",
    "region",
    "latency",
    "ping",
    "server",
    "route",
    "auto best",
    "proxy",
    "vpn",
    "queue",
    "session",
    "sponsor",
    "github sponsor",
    "supporter",
  ],
  "stream-video": [
    "stream",
    "video",
    "quality",
    "codec",
    "fallback",
    "fps",
    "resolution",
    "bitrate",
    "aspect ratio",
    "l4s",
    "cloud gsync",
    "video acceleration",
    "filters",
    "shader",
    "shaders",
    "sharpen",
    "sharpening",
    "saturation",
    "contrast",
    "brightness",
    "vibrance",
    "film grain",
    "post processing",
    "frame interpolation",
    "framegen",
    "model quality",
    "session proxy",
    "community proxy",
    "zortos",
    "identify as console",
    "big picture",
    "gamepad friendly",
    "gfn launch mode",
    "geforce now launch mode",
    "launch games",
  ],
  "stream-recording": [
    "stream",
    "browser",
    "recording",
    "record",
    "capture",
    "resolution",
    "fps",
    "frame rate",
    "bitrate",
    "video",
    "media",
  ],
  "stream-diagnostics": [
    "stream",
    "codec diagnostics",
    "diagnostics",
    "frame stats",
    "stats",
    "hud",
    "overlay",
    "position",
    "session time",
    "session time left",
    "session countdown",
    "session timer",
    "session report",
    "quality report",
    "free tier time",
    "priority time",
    "ultimate time",
    "elapsed counter",
    "counter",
    "performance",
    "decode",
    "decoder",
    "encode",
    "encoder",
    "gpu",
    "cpu",
    "test codecs",
  ],
  "native-streamer": [
    "native",
    "streamer",
    "native streaming",
    "media runtime",
    "backend",
    "directx",
    "dx11",
    "dx12",
    "cloud gsync",
    "experimental",
    "shortcuts",
    "alt-tab",
    "exit",
    "issue",
    "github",
    "discord",
    "report",
    "bug",
  ],
  game: ["game", "language", "keyboard layout", "store", "launch", "graphics settings", "in-game settings", "persistence"],
  audio: ["audio", "microphone", "mic", "push to talk", "voice activity"],
  input: [
    "input",
    "mouse",
    "keyboard layout",
    "shortcut",
    "hotkey",
    "keybind",
    "controls",
    "controller",
    "gamepad",
    "gyro",
    "gyroscope",
    "steam",
    "steam controller",
    "xbox",
    "compatibility",
    "gamecontroller",
    "hid",
    "macos",
    "motion controls",
    "anti afk",
    "pointer lock",
    "native cursor",
    "cursor overlay",
    "server cursor",
    "server-side cursor",
    "recording",
    "screenshot",
  ],
  console: [
    "console",
    "console mode",
    "controller mode",
    "tv mode",
    "console shell",
    "profile picker",
    "ask who's playing",
    "controller",
    "gamepad",
  ],
  interface: [
    "interface",
    "ui",
    "language",
    "locale",
    "translation",
    "app language",
    "accent color",
    "theme color",
    "library",
    "fullscreen",
    "discord",
    "rich presence",
    "poster",
    "anti afk",
    "anti afk indicator",
    "anti afk reminder",
    "afk notification",
    "afk reminder interval",
  ],
  about: [
    "about",
    "update",
    "version",
    "channel",
    "stable",
    "nightly",
    "preview",
    "logs",
    "cache",
    "download",
    "error",
    "report",
    "telemetry",
    "feedback",
    "privacy",
  ],
  thanks: ["thanks", "contributors", "supporters", "sponsors", "community"],
};
