set_source_files_properties(qml/theme/Theme.qml PROPERTIES QT_QML_SINGLETON_TYPE TRUE)
set_source_files_properties(qml/state/ShellStore.qml PROPERTIES QT_QML_SINGLETON_TYPE TRUE)
set_source_files_properties(qml/desktop/components/DesktopTokens.qml PROPERTIES QT_QML_SINGLETON_TYPE TRUE)

qt_add_qml_module(opennow-qt
    URI OpenNOW
    VERSION 1.0
    QML_FILES
        qml/Main.qml
        qml/components/AppChrome.qml
        qml/components/ArtworkSource.qml
        qml/components/ControllerGlyph.qml
        qml/components/FilterDropdown.qml
        qml/components/FocusFrame.qml
        qml/components/GameTile.qml
        qml/components/GlassButton.qml
        qml/components/GlassPanel.qml
        qml/components/HintBar.qml
        qml/components/HomeTileMenu.qml
        qml/components/MotionProgress.qml
        qml/components/NavPill.qml
        qml/components/PageEntrance.qml
        qml/components/PlatformPicker.qml
        qml/components/PosterTile.qml
        qml/components/ReleaseNotes.qml
        qml/components/RoundedArtwork.qml
        qml/components/ScreenBackground.qml
        qml/components/SettingRow.qml
        qml/components/StoreBadge.qml
        qml/components/StreamInputNotice.qml
        qml/components/TogglePill.qml
        qml/components/VirtualKeyboard.qml
        qml/desktop/auth/DesktopSignInScreen.qml
        qml/desktop/components/DesktopBackdrop.qml
        qml/desktop/components/DesktopButton.qml
        qml/desktop/components/DesktopGameModal.qml
        qml/desktop/components/DesktopGlyph.qml
        qml/desktop/components/DesktopKeyHint.qml
        qml/desktop/components/DesktopPoster.qml
        qml/desktop/components/DesktopTokens.qml
        qml/desktop/friends/DesktopFriendsScreen.qml
        qml/desktop/home/DesktopHomePoster.qml
        qml/desktop/home/DesktopHomeScreen.qml
        qml/desktop/library/DesktopLibraryScreen.qml
        qml/desktop/settings/DesktopSettingsScreen.qml
        qml/desktop/settings/controls/DesktopSettingsAdvanced.qml
        qml/desktop/settings/controls/DesktopSettingsButton.qml
        qml/desktop/settings/controls/DesktopSettingsChoice.qml
        qml/desktop/settings/controls/DesktopSettingsDisclosure.qml
        qml/desktop/settings/controls/DesktopSettingsDropdown.qml
        qml/desktop/settings/controls/DesktopSettingsField.qml
        qml/desktop/settings/controls/DesktopSettingsIcon.qml
        qml/desktop/settings/controls/DesktopSettingsPanel.qml
        qml/desktop/settings/controls/DesktopSettingsResolution.qml
        qml/desktop/settings/controls/DesktopSettingsRow.qml
        qml/desktop/settings/controls/DesktopSettingsSection.qml
        qml/desktop/settings/controls/DesktopSettingsSegmented.qml
        qml/desktop/settings/controls/DesktopSettingsSlider.qml
        qml/desktop/settings/controls/DesktopSettingsStepper.qml
        qml/desktop/settings/controls/DesktopSettingsToggle.qml
        qml/desktop/settings/pages/DesktopSettingsAboutPage.qml
        qml/desktop/settings/pages/DesktopSettingsAccountPage.qml
        qml/desktop/settings/pages/DesktopSettingsAudioPage.qml
        qml/desktop/settings/pages/DesktopSettingsConsolePage.qml
        qml/desktop/settings/pages/DesktopSettingsControllersPage.qml
        qml/desktop/settings/pages/DesktopSettingsControlsPage.qml
        qml/desktop/settings/pages/DesktopSettingsInterfacePage.qml
        qml/desktop/settings/pages/DesktopSettingsLookPage.qml
        qml/desktop/settings/pages/DesktopSettingsNetworkPage.qml
        qml/desktop/settings/pages/DesktopSettingsProfilePage.qml
        qml/desktop/settings/pages/DesktopSettingsShortcutsPage.qml
        qml/desktop/settings/pages/DesktopSettingsStatsPage.qml
        qml/desktop/settings/pages/DesktopSettingsStoresPage.qml
        qml/desktop/settings/pages/DesktopSettingsStreamPage.qml
        qml/desktop/settings/pages/DesktopSettingsSubscriptionPage.qml
        qml/desktop/shell/DesktopApp.qml
        qml/desktop/shell/DesktopCommandPalette.qml
        qml/desktop/shell/DesktopShell.qml
        qml/desktop/shell/DesktopSidebar.qml
        qml/desktop/store/DesktopStoreCard.qml
        qml/desktop/store/DesktopStoreChip.qml
        qml/desktop/store/DesktopStoreContent.qml
        qml/desktop/store/DesktopStoreHero.qml
        qml/desktop/store/DesktopStoreShelf.qml
        qml/desktop/stream/DesktopInStreamMenu.qml
        qml/desktop/stream/DesktopSessionStarting.qml
        qml/desktop/stream/DesktopStreamExitConfirm.qml
        qml/desktop/stream/DesktopStreamOverlayHost.qml
        qml/desktop/stream/DesktopStreamScreen.qml
        qml/desktop/stream/DesktopStreamStats.qml
        qml/desktop/updates/DesktopUpdateScreen.qml
        qml/overlays/FriendsOverlay.qml
        qml/overlays/GuideOverlay.qml
        qml/overlays/OverlayHost.qml
        qml/overlays/QueueAdOverlay.qml
        qml/overlays/QuickSettingsOverlay.qml
        qml/overlays/SessionConflictOverlay.qml
        qml/overlays/SessionReportOverlay.qml
        qml/screens/AccountsScreen.qml
        qml/screens/DiagnosticsScreen.qml
        qml/screens/FeedbackScreen.qml
        qml/screens/GameAccountsScreen.qml
        qml/screens/GameDetailScreen.qml
        qml/screens/HomeScreen.qml
        qml/screens/InsertingScreen.qml
        qml/screens/JoiningScreen.qml
        qml/screens/LibraryScreen.qml
        qml/screens/MediaScreen.qml
        qml/screens/PersistentStorageScreen.qml
        qml/screens/ProfilePinScreen.qml
        qml/screens/SettingsScreen.qml
        qml/screens/SignInScreen.qml
        qml/screens/StoreScreen.qml
        qml/screens/StreamScreen.qml
        qml/screens/ThemeStoreScreen.qml
        qml/screens/UpdateScreen.qml
        qml/state/ShellStore.qml
        qml/state/account/AccountServicesState.qml
        qml/state/catalog/ArtworkState.qml
        qml/state/catalog/CatalogState.qml
        qml/state/settings/SettingsState.qml
        qml/theme/Theme.qml
    RESOURCES
        res/icons/nav-home.svg
        res/icons/nav-library.svg
        res/icons/nav-controller.svg
        res/icons/nav-friends.svg
        res/icons/nav-settings.svg
        res/icons/nav-computer.svg
        res/icons/settings-account.svg
        res/icons/settings-streaming.svg
        res/icons/settings-video.svg
        res/icons/settings-input.svg
        res/icons/settings-network.svg
        res/icons/settings-themes.svg
        res/icons/settings-advanced.svg
        res/icons/store-steam.svg
        res/icons/store-xbox.svg
        res/icons/store-gog.svg
        res/icons/store-gaijin.svg
        res/icons/store-ea.svg
        res/icons/store-nvidia.svg
        res/icons/store-nvidia.svg
        res/icons/store-epic.svg
        res/icons/store-ubisoft.svg
        res/icons/store-battlenet.svg
        res/brand/opennow-mark.png
        res/brand/signin-hero.jpg
        res/brand/desktop-renew.jpg
        res/fonts/Nunito-Variable.ttf
        res/fonts/IBMPlexMono-Regular.ttf
        res/fonts/IBMPlexMono-Medium.ttf
        res/fonts/IBMPlexMono-Bold.ttf
        res/icons/desktop-nav-home.svg
        res/icons/desktop-nav-home-active.svg
        res/icons/desktop-nav-library.svg
        res/icons/desktop-nav-library-active.svg
        res/icons/desktop-nav-store.svg
        res/icons/desktop-nav-store-active.svg
        res/icons/desktop-nav-friends.svg
        res/icons/desktop-nav-friends-active.svg
        res/icons/desktop-nav-settings.svg
        res/icons/desktop-nav-settings-active.svg
        res/icons/desktop-collapse.svg
        res/icons/desktop-expand.svg
        res/icons/desktop-plus.svg
        res/icons/desktop-star.svg
        res/icons/desktop-clock.svg
        res/icons/desktop-coop.svg
        res/icons/desktop-rtx.svg
        res/icons/desktop-gamepad.svg
        res/icons/desktop-chevron-up.svg
        res/icons/desktop-chevron-down.svg
        res/icons/desktop-search.svg
        res/icons/desktop-nav-home-on-light.svg
        res/icons/desktop-nav-home-active-on-light.svg
        res/icons/desktop-expand-on-light.svg
        res/icons/desktop-star-on-light.svg
        res/icons/desktop-gamepad-on-light.svg
        res/icons/desktop-chevron-up-on-light.svg
        res/icons/desktop-rtx-on-light.svg
        res/icons/desktop-search-on-light.svg
        res/icons/desktop-nav-store-on-light.svg
        res/icons/desktop-nav-store-active-on-light.svg
        res/icons/desktop-collapse-on-light.svg
        res/icons/desktop-nav-settings-on-light.svg
        res/icons/desktop-nav-settings-active-on-light.svg
        res/icons/desktop-plus-on-light.svg
        res/icons/desktop-nav-library-on-light.svg
        res/icons/desktop-nav-library-active-on-light.svg
        res/icons/desktop-coop-on-light.svg
        res/icons/desktop-nav-friends-on-light.svg
        res/icons/desktop-nav-friends-active-on-light.svg
        res/icons/desktop-clock-on-light.svg
        res/icons/desktop-play.svg
        res/icons/desktop-lock.svg
        res/icons/desktop-check.svg
        res/icons/desktop-shield.svg
        res/icons/desktop-qr.svg
        res/icons/desktop-info.svg
        res/icons/desktop-close.svg
        res/icons/desktop-folder.svg
        res/icons/desktop-check-mint.svg
        res/icons/desktop-check-light.svg
        res/icons/desktop-check-focus.svg
        res/icons/desktop-message.svg
        res/icons/desktop-sliders.svg
        res/icons/desktop-user-plus.svg
        res/icons/desktop-logout.svg
        res/icons/desktop-plus-ink.svg
        res/icons/desktop-mic.svg
        res/icons/desktop-mic-off.svg
        res/icons/desktop-play-stroke.svg
)
