set(OPENNOW_STREAM_RUNTIME_SOURCES
    src/streaming/NativeStreamRuntime.cpp
    src/streaming/NativeStreamRuntime.h
)

set(OPENNOW_STREAM_PRESENTATION_SOURCES
    src/streaming/StreamVideoItem.cpp
    src/streaming/StreamVideoItem.h
    src/streaming/StreamVideoItemInput.cpp
    src/streaming/rendering/LinuxVulkanGraphics.cpp
    src/streaming/rendering/LinuxVulkanGraphics.h
    src/streaming/rendering/NativeStreamRenderCallback.cpp
    src/streaming/rendering/NativeStreamRenderCallback.h
    src/streaming/rendering/StreamVideoItemRendering.cpp
    src/streaming/rendering/StreamVideoRenderCallback.h
    src/streaming/rendering/StreamVideoTextureRenderer.h
    src/streaming/rendering/StreamFrameInterpolator.cpp
    src/streaming/rendering/StreamFrameInterpolator.h
    src/streaming/rendering/StreamFramePacer.h
)

qt_add_executable(opennow-qt
    src/main.cpp
    src/acceptance/AcceptanceProfiler.cpp
    src/acceptance/AcceptanceProfiler.h
    src/acceptance/AcceptanceSession.cpp
    src/acceptance/AcceptanceSession.h
    src/acceptance/MotionAcceptance.cpp
    src/acceptance/MotionAcceptance.h
    src/acceptance/SmokeAcceptance.cpp
    src/acceptance/SmokeFixtures.cpp
    src/app/AppController.cpp
    src/app/AppController.h
    src/app/ApplicationStartup.cpp
    src/app/ApplicationStartup.h
    src/app/SingleInstance.cpp
    src/app/SingleInstance.h
    src/core/CoreClient.cpp
    src/core/CoreClient.h
    src/diagnostics/DiagnosticsPaths.h
    src/input/ControllerInput.cpp
    src/input/ControllerInput.h
    src/input/InputModeTracker.cpp
    src/input/InputModeTracker.h
    src/localization/Localization.cpp
    src/localization/Localization.h
    src/media/ThumbnailGenerator.cpp
    src/media/ThumbnailGenerator.h
    ${OPENNOW_STREAM_RUNTIME_SOURCES}
    ${OPENNOW_STREAM_PRESENTATION_SOURCES}
)
