<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <RootNamespace>OpenNow.Playnite</RootNamespace>
    <AssemblyName>OpenNow.Playnite</AssemblyName>
    <LangVersion>latest</LangVersion>
    <UseWPF>true</UseWPF>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>bin\Debug\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>bin\Release\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PlayniteSDK" Version="6.13.0" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="app.xaml" />
    <Page Include="OpenNowSettingsView.xaml" />
    <Page Include="Views\DatabaseBrowserView.xaml" />
  </ItemGroup>

  <ItemGroup>
    <None Include="extension.yaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="icon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Localization\en_US.xaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <Target Name="CopyLocalization" AfterTargets="Build">
    <Copy SourceFiles="$(ProjectDir)Localization\en_US.xaml" DestinationFolder="$(TargetDir)Localization\" SkipUnchangedFiles="true" />
  </Target>
</Project>
