file(STRINGS "${CMAKE_CURRENT_LIST_DIR}/windows-release-binaries.txt"
    OPENNOW_WINDOWS_RELEASE_BINARIES)
foreach(OPENNOW_WINDOWS_RELEASE_BINARY IN LISTS OPENNOW_WINDOWS_RELEASE_BINARIES)
    if(NOT OPENNOW_WINDOWS_RELEASE_BINARY STREQUAL "${OPENNOW_EXECUTABLE_NAME}.exe")
        install(PROGRAMS
            "$<TARGET_FILE_DIR:opennow-qt>/${OPENNOW_WINDOWS_RELEASE_BINARY}"
            DESTINATION "${CMAKE_INSTALL_BINDIR}")
    endif()
endforeach()
