name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug and how to reproduce it
      placeholder: |
        What went wrong?

        Steps to reproduce (if applicable):
        1. ...
        2. ...
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Windows
        - Linux
    validations:
      required: true

  - type: dropdown
    id: tier
    attributes:
      label: GeForce NOW Tier
      options:
        - Free
        - Performance
        - Ultimate
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs (required)
      description: |
        Please export and attach your logs:
        1. Open Settings (gear icon)
        2. Scroll to Troubleshooting section
        3. Click "Export Logs"
        4. Drag the exported .log file here or paste its contents

        Logs help us debug your issue much faster!
      placeholder: Drag your exported log file here or paste the contents...
      render: shell
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (optional)
      description: If applicable, add screenshots to help explain your problem
