name: Documentation
description: Report missing, incorrect, or unclear documentation
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Help us improve our documentation!

  - type: dropdown
    id: type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect/outdated documentation
        - Unclear/confusing documentation
        - Typo/grammatical error
        - New documentation request
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation located? (file path, URL, or section name)
      placeholder: e.g., README.md, docs/setup.md, Wiki page name
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the documentation issue or what documentation is needed
      placeholder: Describe the issue...
    validations:
      required: true

  - type: textarea
    id: suggested-change
    attributes:
      label: Suggested Change
      description: If you have a suggestion for how to fix or improve the documentation
      placeholder: Your suggestion...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help improve the documentation?
      options:
        - label: I am willing to submit a pull request to update the documentation
