name: Question
description: Ask a question about GFNClient
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Your Question
      placeholder: What would you like to know?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context (optional)
      description: OS, version, what you've tried, etc.
