export const FRAME_GENERATION_TEXTURE_POOL_SIZE = 8;
export const FRAME_GENERATION_HISTORY_TEXTURE_RESERVE = 1;
export const FRAME_GENERATION_IN_FLIGHT_TEXTURE_RESERVE = 2;

export const FRAME_GENERATION_PRESENTATION_QUEUE_CAPACITY =
  FRAME_GENERATION_TEXTURE_POOL_SIZE
  - FRAME_GENERATION_HISTORY_TEXTURE_RESERVE
  - FRAME_GENERATION_IN_FLIGHT_TEXTURE_RESERVE;
