export {
  INPUT_HEARTBEAT,
  INPUT_KEY_DOWN,
  INPUT_KEY_UP,
  INPUT_LOCK_KEYS_SYNC,
  INPUT_MOUSE_ABS,
  INPUT_MOUSE_REL,
  INPUT_MOUSE_BUTTON_DOWN,
  INPUT_MOUSE_BUTTON_UP,
  INPUT_MOUSE_WHEEL,
  INPUT_GAMEPAD,
  INPUT_HAPTICS_ENABLED,
  INPUT_TEXT,
  WRAPPER_VERSION_MARKER,
  WRAPPER_SINGLE_INPUT,
  restampProtocolV3OuterTimestamp,
  combineSingleInputPackets,
  finalizeReliableSingleInputPackets,
  MOUSE_LEFT,
  MOUSE_MIDDLE,
  MOUSE_RIGHT,
  MOUSE_BACK,
  MOUSE_FORWARD,
  PARTIALLY_RELIABLE_GAMEPAD_MASK_ALL,
  PARTIALLY_RELIABLE_HID_DEVICE_MASK_ALL,
  partiallyReliableHidMaskForInputType,
  isPartiallyReliableHidTransferEligible,
  InputEncoder,
  toMouseButton,
} from "./packetEncoding";
export type {
  MouseMovePayload,
  MouseAbsolutePayload,
  MouseButtonPayload,
  MouseWheelPayload,
} from "./packetEncoding";

export {
  codeMap,
  mapTextCharToKeySpec,
  shiftModifierByte,
  modifierFlags,
  lockKeysStateFromEvent,
  mapKeyboardEvent,
} from "./keyboardMapping";
export type { KeyboardPayload, KeyMapping, TextKeySpec } from "./keyboardMapping";

export {
  GAMEPAD_DPAD_UP,
  GAMEPAD_DPAD_DOWN,
  GAMEPAD_DPAD_LEFT,
  GAMEPAD_DPAD_RIGHT,
  GAMEPAD_START,
  GAMEPAD_BACK,
  GAMEPAD_LS,
  GAMEPAD_RS,
  GAMEPAD_LB,
  GAMEPAD_RB,
  GAMEPAD_GUIDE,
  GAMEPAD_A,
  GAMEPAD_B,
  GAMEPAD_X,
  GAMEPAD_Y,
  GAMEPAD_AXIS_LX,
  GAMEPAD_AXIS_LY,
  GAMEPAD_AXIS_RX,
  GAMEPAD_AXIS_RY,
  GAMEPAD_AXIS_LT,
  GAMEPAD_AXIS_RT,
  GAMEPAD_MAX_CONTROLLERS,
  GAMEPAD_PACKET_SIZE,
  GAMEPAD_DEADZONE,
  applyDeadzone,
  normalizeToInt16,
  normalizeToUint8,
  mapGamepadButtons,
  readGamepadAxes,
} from "./gamepadMapping";
export type { GamepadInput } from "./gamepadMapping";

export {
  startInputSessionClock,
  captureTimestampUs,
  sendTimestampUs,
} from "./inputSessionClock";
